// Generated by https://quicktype.io

export interface Student {
  id:    string;
  name:  string;
  lastname: string;
  birthday: null;
  curp: string;
  created: null;
  modified: null;
  deleted: null;
  active: boolean;
}

export enum Institute {
  Mexico = "Mexico City",
  Canada = "Vancouver Canada",
}
